const constants = {
  FLIGHTS_NEW_POSITION: "FLIGHTS_NEW_POSITION",
  FLIGHTS_NEW_POSITION_REJECTED: "FLIGHTS_NEW_POSITION_REJECTED",
  FLIGHTS_FULFILLED: "FLIGHTS_FULFILLED",
  FLIGHTS_REJECTED: "FLIGHTS_REJECTED",
};

export default constants;
